version: '2.3'

services:
  good-ssh:
    image: krlmlr/debian-ssh
    container_name: debian-ssh

  good-telnet:
    image: ddhhz/nyancat-server
    container_name: telnet

  good-ftp:
    image: bogem/ftp
    container_name: ftp

  good-http:
    image: httpd
    container_name: http
