version: '2.3'


services:
  amun:
    build: ./amun
    container_name: amun

  beartrap:
    build: ./beartrap
    container_name: breatrap

  cowrie:
    build: ./cowrie
    container_name: cowrie

  honeypy:
    build: ./honeypy
    container_name: honeypy
    cap_add:                                                                                                                                                                
      - NET_ADMIN

  mtpot:
    build: ./mtpot
    container_name: mtpot

  dionaea:
    image: dtagdevsec/dionaea:1903
    container_name: dionaea

  kippo:
    build: ./kippo
    container_name: kippo

  telnetlogger:
    image: txt3rob/docker-telnet-logger
    container_name: telnetlogger

# Tanner Redis Service
  tanner_redis:
    build: ./redis
    container_name: tanner_redis
    stop_signal: SIGKILL
    tty: true
    image: "mushorg/redis:latest"
    read_only: true

# PHP Sandbox service
  tanner_phpox:
    build: ./phpox
    container_name: tanner_phpox
    stop_signal: SIGKILL
    tty: true
    image: "mushorg/phpox:latest"
    read_only: true
    tmpfs: "/tmp"

# Tanner API Service
  tanner_api:
    build: ./tanner
    container_name: tanner_api
    stop_signal: SIGKILL
    tmpfs:
     - /tmp/tanner:uid=65534,gid=65534
     - /var/log/tanner:uid=65534,gid=65534
    tty: true
    image: "mushorg/tanner:latest"
    read_only: true
    command: tannerapi 
    depends_on:
     - tanner_redis

# Tanner WEB Service
  tanner_web:
    build: ./tanner
    container_name: tanner_web
    stop_signal: SIGKILL
    tmpfs:
     - /tmp/tanner:uid=65534,gid=65534
     - /var/log/tanner:uid=65534,gid=65534
    tty: true
    ports:
     - "8091:8091"
    image: "mushorg/tanner:latest"
    command: tannerweb
    read_only: true
    depends_on:
     - tanner_redis

# Tanner Service
  tanner:
    build: ./tanner
    container_name: tanner
    stop_signal: SIGKILL
    tmpfs:
     - /tmp/tanner:uid=65534,gid=65534
     - /var/log/tanner:uid=65534,gid=65534
     - /opt/tanner/files:uid=65534,gid=65534
    tty: true
    ports:
     - "8090:8090"
    image: "mushorg/tanner:latest"
    command: tanner
    read_only: true
    depends_on:
     - tanner_api
     - tanner_web

# Snare service
  snare:
    build: ./snare
    container_name: snare
    stop_signal: SIGKILL
    tty: true
    ports:
     - "80:80"
    image: "mushorg/snare:latest"

  

  
